[all_hosts]
adminhost    ansible_host=YOUR_PROD_ADMIN_IP
sqlserver    ansible_host=YOUR_PROD_SQL_IP
workstation1 ansible_host=YOUR_PROD_WS1_IP
workstation2 ansible_host=YOUR_PROD_WS2_IP

[sqlserver]
sqlserver

[workstations]
workstation1
workstation2

[all_hosts:vars]
ansible_user=ubuntu # Стандартный пользователь для AWS/Ubuntu Cloud
ansible_password="{{ vault_ansible_password }}"
ansible_become_password="{{ vault_ansible_become_password }}"