---

- name: Настрока не админиских хостов
  hosts: all:!adminhost
  become: true
  tasks:
    - name: Создание папки для монтирования
      ansible.builtin.file:
        path: /home/{{ ansible_user_id }}/honeylogs
        state: directory
        mode: '0777'

    - name: Создание файла для сбора логов с контейнера
      ansible.builtin.file:
        path: /home/{{ ansible_user_id }}/honeylogs/ssh_logs.log
        state: touch
        mode: '0666'

    - name: Сборка образа SSH-ханипота из Dockerfile
      community.docker.docker_image:
        name: my_ssh_honeypot
        build:
          path: ./path/to/ssh_honeypot_folder
        source: build

    - name: Запуск SSH контейнера на порту 22
      docker_container:
        name: ssh_honeypot
        image: my_ssh_honeypot
        state: started
        restart_policy: always
        ports:
          - "22:22"
        volumes:
          - "/home/{{ ansible_user_id }}/honeylogs/ssh_logs.log:/app/ssh_honeypot.log"
    
    - name: Создание конфигурации для отправки логов
      copy:
        dest: /etc/rsyslog.d/honeypot.conf
        content: |
          module(load="imfile" Mode="inotify")

          # Указываем следить за лог-файлом ханипота
          input(type="imfile"
            File="/home/{{ ansible_user_id }}/honeylogs/ssh_logs.log"
            Tag="honeypot"
            Severity="info"
            Facility="local7")

          # Отправляем всё на центральный сервер по TCP
          action(type="omfwd"
            Target="192.168.56.30"
            Port="514"
            Protocol="tcp"
            queue.type="linkedList"
            queue.size="10000")
        mode: '0644'
          
- name: Настройка MySQL сервера
  hosts: mysqlserv
  become: true
  tasks:
    - name: Установка MySQL сервера
      apt:
        name:
          - mysql-server
          - mysql-client
        state: present
        update_cache: yes

    - name: Изменение порта MySQL в конфигурации
      lineinfile:
        path: /etc/mysql/mysql.conf.d/mysqld.cnf
        regexp: '^#?port\s*='
        line: 'port = 3333'
      notify: restart_mysql

    - name: Запуск MySQL сервера
      systemd:
        name: mysql
        state: started
        enabled: yes

    - name: Создание папки для монтирования
      ansible.builtin.file:
        path: /home/{{ ansible_user_id }}/honeylogs
        state: directory
        mode: '0777'

    - name: Создание файла для сбора логов с контейнера
      ansible.builtin.file:
        path: /home/{{ ansible_user_id }}/honeylogs/mysql_logs.log
        state: touch
        mode: '0666'


    - name: Сборка образа mysql-ханипота из Dockerfile
      community.docker.docker_image:
        name: my_mysql_honeypot
        build:
          path: ./path/to/mysql_honeypot_folder
        source: build

    - name: Запуск MySQL контейнера на порту 3306
      docker_container:
        name: mysql_honeypot
        image: my_mysql_honeypot
        state: started
        restart_policy: always
        ports:
          - "3306:3306"
        volumes:
          - "/home/{{ ansible_user_id }}/honeylogs/mysql_logs.log:/app/mysql_honeypot.log"
        env:
          MYSQL_ROOT_PASSWORD: "rootpassword"
          MYSQL_DATABASE: "appdb"
          MYSQL_USER: "appuser"
          MYSQL_PASSWORD: "apppassword"
        networks:
          - name: bridge

    - name: Создание конфигурации для отправки логов
      copy:
        dest: /etc/rsyslog.d/honeypot.conf
        content: |
          module(load="imfile" Mode="inotify")

          # Указываем следить за лог-файлом ханипота
          input(type="imfile"
            File="/home/{{ ansible_user_id }}/honeylogs/mysql_logs.log"
            Tag="honeypot"
            Severity="info"
            Facility="local7")

          # Отправляем всё на центральный сервер по TCP
          action(type="omfwd"
            Target="192.168.56.30"
            Port="514"
            Protocol="tcp"
            queue.type="linkedList"
            queue.size="10000")
        mode: '0644'
      notify: restart rsyslog
    
  handlers:
    - name: restart rsyslog
      service:
        name: rsyslog
        state: restarted
        enabled: yes
    
    - name: restart mysql
      service:
        name: MySQL
        state: restarted
        enabled: yes


- name: Настройка рабочих станций
  hosts: workstations
  become: true
  tasks:
    - name: Создание папки для монтирования
      ansible.builtin.file:
        path: /home/{{ ansible_user_id }}/honeylogs
        state: directory
        mode: '0777'

    - name: Создание файла для сбора логов с контейнера
      ansible.builtin.file:
        path: /home/{{ ansible_user_id }}/honeylogs/telnet_logs.log
        state: touch
        mode: '0666'

    - name: Сборка образа telnet-ханипота из Dockerfile
      community.docker.docker_image:
        name: my_telnet_honeypot
        build:
          path: ./path/to/mytelnet_honeypot_folder
        source: build

    - name: Запуск telnet контейнера на порту 23
      docker_container:
        name: telnet_honeypot
        image: my_telnet_honeypot
        state: started
        restart_policy: always
        ports:
          - "23:23"
        volumes:
          - "/home/{{ ansible_user_id }}/honeylogs/telnet_logs.log:/app/telnet_honeypot.log"

    - name: Создание конфигурации для отправки логов
      copy:
        dest: /etc/rsyslog.d/honeypot.conf
        content: |
          module(load="imfile" Mode="inotify")

          # Указываем следить за лог-файлом ханипота
          input(type="imfile"
            File="/home/{{ ansible_user_id }}/honeylogs/telnet_logs.log"
            Tag="honeypot"
            Severity="info"
            Facility="local7")

          # Отправляем всё на центральный сервер по TCP
          action(type="omfwd"
            Target="192.168.56.30"
            Port="514"
            Protocol="tcp"
            queue.type="linkedList"
            queue.size="10000")
        mode: '0644'
      notify: restart rsyslog

  handlers:
    - name: restart rsyslog
      service:
        name: rsyslog
        state: restarted
        enabled: yes


- name: Настройка хоста администратора
  hosts: adminhost
  become: true
  tasks:
      - name: Создание конфигурации для ПРИЁМА логов (сервер)
        copy:
          dest: /etc/rsyslog.d/server.conf
          content: |
            module(load="imtcp")
            input(type="imtcp" port="514")
            $template RemoteLogs,"/var/log/honeypots/%HOSTNAME%/%PROGRAMNAME%.log"
            *.* ?RemoteLogs
            & stop
          mode: '0644'
        notify: restart rsyslog

      - name: Настройка rsyslog для создания директорий
        lineinfile:
          path: /etc/rsyslog.conf
          line: '$CreateDirs on'
          state: present
        notify: restart rsyslog

      - name: Создание директории для хранения логов ханипотов
        file:
          path: /var/log/honeypots
          state: directory
          owner: syslog
          group: adm
          mode: '0755'

      - name: Открытие порта 514 в фаерволе 
        ufw:
          rule: allow
          port: '514'
          proto: tcp
        when: ansible_facts.os_family == "Debian"
        ignore_errors: yes

  handlers:
    - name: restart rsyslog
      service:
        name: rsyslog
        state: restarted
        enabled: yes

- name: Общая настройка для всех хостов
  hosts: all
  become: true
  tasks:
    - name: Установка зависимостей для Docker
      apt:
        name: "{{item}}"
        state: present
        update_cache: yes
      loop:
        - apt-transport-https
        - ca-certificates
        - curl
        - gnupg-agent
        - software-properties-common

    - name: Добавление официального GPG ключа Docker
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Добавление репозитория Docker
      apt_repository:
        repo: "deb [arch=amd64] https://download.docker.com/linux/{{ ansible_distribution | lower }} {{ ansible_distribution_release }} stable"
        state: present

    - name: Установка Docker
      apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
        state: latest

    - name: Установка Docker модуля для Python
      apt:
        name: python3-docker
        state: present

    - name: Добавление пользователя vagrant в группу docker
      user:
        name: vagrant
        groups: docker
        append: yes

    - name: Перенастройка SSH сервера на порт 2222
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^#?Port '
        line: 'Port 2222'
      notify: restart_ssh

    - name: Обновление порта для текущей сессии
      set_fact:
        ansible_port: 2222

    - name: Установка rsyslog
      apt:
        name: rsyslog
        state: present
        update_cache: yes
    
  handlers:
  - name: restart_ssh
    systemd:
      name: ssh
      state: restarted
